### PR TITLE
LPS-69917 Format the average score in page.jsp according the javascript

### PR DESCRIPTION
**Pull request by cleydyr**
/cc @rodrigopaulino 
Relevant issue: https://issues.liferay.com/browse/LPS-69917

### CODE REVIEW

**Comment by dsanz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dsanz** [comment]
Hi @cleydyr I saw this and realized that I couldn't review it on time.

How urgent is it? I have a bunch of tasks for this and next week so I think it's better if we sent this one to @robertoDiaz

**Comment by cleydyr** [comment]
Hi, @dsanz. It's not urgent at all. I see that this is a rather cosmetic change, so it's not urgent at all. I'll forward this PR to Roberto as he's now the SME for this component.

Thank you.

**Comment by robertoDiaz** [comment]
I'm reviewing this.

Thank you guys!!

**Pull request closed without merging**
