### PR TITLE
LPS-67837

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Daneil,
Could you help to review this pull request? one ee customer is waiting for this fix
Thanks

**Comment by dsanz** [comment]
Hi @daledotshan I've answered the email sent by Hugo with instructions about how to proceed. Please forward this to Bchan

**Comment by daledotshan** [comment]
Hey Daneil,
Probably you understand wrong, this pull request not related to language translation

**Comment by dsanz** [comment]
Hi Dale,

I'm a bit confused, the PR modifies transation files. How is it possible that this is not related to translations?

I've read the LPS and seems that the origin of this is that we've unpublished a MK app, but I can't see why this makes things different regarding the PR itself.

If we need to provide this new message via a change in the meaning of a translation key, then we're stil having a transation PR.

As I can't review the content itself (i.e. the meaning), the only concerns to be taken into account are the file encoding and the proper pootle updates.

Am I missing something?
Please let me know

Thanks so much

**Comment by daledotshan** [comment]
Hey Daneil,
yes, I think you are right this issue partly related to translation

@sherlyliu  Could you please add the translation on translation.liferay.com?

**Comment by dsanz** [comment]
Hi Dale,

after thinking a bit about this, maybe I misinterpreted your request. Maybe you guys are asking me to look at the English texts or try how portal looks like with those translations. I can help with that if you guys need.

Please let me know

Best

**Comment by daledotshan** [comment]
Hey Daneil,
yeah we are asking you to look at the English texts.
Thanks,
Dale

**Comment by dsanz** [comment]
Hi Dale,

I'm really sorry for the misunderstanding. Let me take a look to them and come back to you

Kind regards

**Comment by dsanz** [comment]
Hi Dale,

the English text seems correct to me. 

My only concern is about the messaging itself. As the PR is for master, I understand we can not suggest user to open a support ticket (we could do this only in the EE/DE versions). But, is there anything we can tell users, like watch some community forum or stay tuned to the MK news?

Besides that, I don't see any issue

Best

**Comment by sherlyliu** [comment]
Hi Daneil,

About the message change I have post a thread in froum, Nicole suggested we should change the message: https://in.liferay.com/web/support/forums/-/message_boards/message/24047235

**Pull request closed without merging**
