### PR TITLE
LPS-69811

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by dsanz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by holatuwol** [comment]
ci:reopen

**Comment by NolanChan** [comment]
I did some initial testing and everything seems to line up well: I tested the portlet in LPS-69002 with the hyphens in the name and those were stripped correctly. I also tested the portlet with periods in the name in LPP-23747 and that worked as well too (converted periods to underscores). However more confirmation is much appreciated 👍

**Comment by dsanz** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1270. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
