### PR TITLE
LPS-55767

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hi Daniel,

I figured that this pull request would be best to go to you since it is dealing with translations, but let me know if it should go somewhere else.

It seems that an incorrect translation was added under 93961a036a88a9819e10cad0ea785c8e92240798 Let me know if you have any questions.

Thanks

/cc @samziemer

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by dsanz** [comment]
Hi @jonathanmccann ,

I've change that in pootle as well. If en_GB translation equals to en_US one, then the solution is to remove the line containing that translation in Language_en_GB.properties, as en_GB is a child language of en_US. 

The origin of this seems an old pootle bug.

No need to retest as this is a translation change.

Could you please resend to BChan just removing the aforementioned line?

Thanks so much!

**Comment by jonathanmccann** [comment]
Hi Daniel,

Thanks for the response, I'll forward it on to Brian.

Thanks!

**Pull request closed without merging**
