### PR TITLE
LPS-65895

### PR DESCRIPTION
**Pull request by juangon**
/cc  @sherlyliu

### CODE REVIEW

**Comment by juangon** [comment]
Hi @dsanz, can you review and forward to Maté if approved? Thanks!

**Comment by matethurzo** [comment]
@dsanz @juangon guys this change will cause regressions. There is a different conversation thread for this with @sergiogonzalez and we will need to involve PM as well because the solution needs business evaluation too.

So please don't push this forward.

**Comment by juangon** [comment]
Thanks @matethurzo. Can you tell briefly what would be the regression? This was supposed to go to fixpacks and customer patches and would be great if we could apply this for them too or would be too risky.

**Comment by juangon** [comment]
BTW I checked that this pull doesn't cause the regression you mentioned here: https://github.com/matethurzo/liferay-portal/pull/1489#issuecomment-221018499. Are you talking about other regression?

**Comment by zsigmondrab** [comment]
Hi Guys,

I think, we still can have the problem with the page titles. This will fail if there is a wiki page already with different uuid but with the same title. But let me know if I miss anything.

If I am right we should implement something for handling that similarly to how it is implemented in case of the FileEntryStagedModelDataHandler. See the getSanitizedFileName method usage at

https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-service/src/main/java/com/liferay/document/library/lar/FileEntryStagedModelDataHandler.java#L539-L541 and at
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/util/DLImpl.java#L650-L673

If I am right, we should find something out for the wiki pages.

Let me know if I am missing anything.

Thank you,
Zsigmond

**Comment by dsanz** [comment]
That's a difficult thing for wikipages as titles are the ids. 

If we move the original page to "make room" for the new one, then we'd keep the old name as an "alias" for the new name. That's why links to the old name still work.

As a result, we would not be making any room for the new page as the original name still exist.

The only option I see is to use incremental names like "ExisingPageName1", "ExisingPageName2" etc. That's the most elegant way to keep existing stuff untouched, yet creating new pages as a result of "Copy as new" option.

However, this poses some problems too: if you create a wikipage using a different name than its original name, then we would be breaking all incoming links to that page in Live as they will point to the old name.

We can fix this too during import, but I'd recommend a careful analysis and (above all) testing.

Best

**Comment by zsolah** [comment]
Hi @dsanz

The problem you described can only happen when a "Main node" is being imported using copy as new. Because only in this case we are trying to update the existing Main node. I think we should consider changing the behavior for Main node by removing [these lines](https://github.com/juangon/liferay-portal/blob/3f230ecb2db219a69d262b145d8ac1ce32ad1098/modules/apps/collaboration/wiki/wiki-service/src/main/java/com/liferay/wiki/lar/WikiNodeStagedModelDataHandler.java#L155-L164), so when using copy as new , for Main nodes there will be a new Main node 2 etc. created.

If this is not viable the we have to incorporate the data strategy check into wikiPage as well, and make a new getPageName logic, to generate new page name, when importing a main node using copy as new.

Regards.

**Comment by dsanz** [comment]
Hi @zsolah that makes sense. The thing is that now I'm not sure about who will take next action item and in what direction.

On one side, this issue seems to cause a regression and the fix require PM review. On the other side @juangon checked that the fix is not related to the regression, and @zsigmondrab pointed out a possible case to be taken into account.

@sergiogonzalez , @matethurzo do you plan to contact PM to review this?

I think it does not make any sense to think about these changes if it requires PM approval. But I'm uncertain about this fact too as we may be talking about 2 different issues.

Can someone shed some light?
Thanks soooo much :)

**Comment by matethurzo** [comment]
@dsanz yes that's the plan, I've mentioned it already somewhere that we need to contact the PM to discuss. I'll cc you.

**Comment by dsanz** [comment]
Thanks @matethurzo , I'll keep an eye on this!

Best

**Pull request closed without merging**
