### PR TITLE
LPS-102379 When Italian is set as display language, the Export User functionality will not work

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @dsanz,

could you plesae check my changes? 

Thanks, Roland

https://issues.liferay.com/browse/LPS-102379

### CODE REVIEW

**Comment by jbalsas** [comment]
Just a thought, not sure what would be the best path, this or `HtmlUtil.escapeJS`...

**Comment by rolandpakai** [comment]
Hi @jbalsas, @dsanz 

could you please check my changes and push it to the master?

Thanks, Roland

**Comment by dsanz** [comment]
Hi Roland,

if the issue is that our JS code must escape the aphostrophes from what <liferay-ui:message> returns, in order to produce apostrophe-free strings that can be passed as parameters to functions, then I'm afraid that the problem scope is a bit bigger.

In a fresh pulled master, IntelliJ reports 367 occurrences of the string `'<liferay-ui:message` in fille pattern \*.js\* (that is, js and jsp files). There are ton of places where we populate js object fields with values coming from `<liferay-ui:message>`, not to mention calls to functions like `alert()` or, as you originally identified, `confirm()`. Most, if not all of them, appear in -web or -taglib modules. I found another 25 cases in master-private

That's roughly 15% of the total number of occurrences of '<liferay-ui:message' (w/o the first apostrophe) given by intelliJ for master (2900) and master-private (278).

To properly fix this, we might target all these. I don't see a reliable mechanism to avoid part of this, unless we can guarantee that all translations of a given key will not have apostrophe.

I'm not sure either about the best approach as our goal is to generate proper JS code, maybe escapeJS would fit better. MessageTag seems not to support this directly via attributes.

What do you guys think?
cc/ @jbalsas @antonio-ortega

**Comment by rolandpakai** [comment]
Hi @dsanz ,

thanks for checking all the occurence of the '<liferay-ui:message - i was able to find them too - but i tryed to concentrate only the ones which are used in the confirm JS function - which will solve the customer issue.

Maybee we can fix this in the liferay-ui:message taglib by unicode by default the message - but i dont know what regression could cause this major change in a widely used taglib.

Roland

**Comment by dsanz** [comment]
I see Roland, thanks for the confirmation.

We may want to change this little by little, for example, fix this for confirm(), then alert(), then JS objects that get populated with the result of <liferay-ui:message>

I'm a bit hesitant to change the taglib behavior. Retrieving translations with unicode entails invoking the [UnicodeFormatter.toString()](https://github.com/liferay/liferay-portal-ee/blob/02d55c884eef0b6d03523e49eeeafb1506e76710/portal-kernel/src/com/liferay/portal/kernel/util/UnicodeFormatter.java#L134) each time, which changes all characters in the string by their unicode hex representation and may be expensive when not needed.

There is a hack in the MessageTag class, which enables unicode in [presence of a request parameter](https://github.com/liferay/liferay-portal-ee/blob/20b4ac9aaff1739f111e8f42cdda426d6363732d/util-taglib/src/com/liferay/taglib/ui/MessageTag.java#L52-L53) set by the <aui:script> tag. Problem is that not all occurrences of our scripts in JSPs are enclosed in <aui:script>. We use <script> often times too.

This means that this is not a new problem, but, it's only partially solved. Some ocurrences of confirm() happen within <aui:script> so changing them is redundant and would potentially create misunderstandings.

At this point, I'm not certain about what's the best strategy. We have a mechanism, but it's not used everywhere. Setting the taglib attribute should happen only when aui:script is not enclosing the JS code.

Therefore, to be able to patch this for the customer, I'd focus on their specific case and fix it only in the confirm() functions outside <aui>. According to my findings, that happens only once, just the one found by customer :), it's in <liferay-util:buffer>

Then, with the help of @antonio-ortega and @jbalsas , decide about topics like:
- Default tag behavior
- Change all the invocations outside <aui:tag> (generic <script> tags, <buffer> may enable the request parameter too,...)
- Document this so that developers are aware
- Caching unicode transformations for requested keys to avoid reencoding the same string over and over again

Hope this makes sense to you guys.

**Comment by jbalsas** [comment]
Hey @dsanz, as I stated above, could you check to see if `HtmlUtil.escapeJS` fixes the issue? In order to escape properly we need context. That's why making the tag always unicode feels so wrong and clearly overkill.

We would only need to escape when in the context of JS, which we should likely do anyways.

**Comment by dsanz** [comment]
Hi @jbalsas 

Yeah we can try that instead of setting `<liferay-ui:message unicode=true>` to fix this. MessageTag does not invoke escapeJS so there is no way to get it done by passing parameters to the taglib call. We'll need to do this by a "regular" call to the taglib and escaping the result in the JSP itself. @rolandpakai can we try this for the fix in question? According to my previous findings, it's enough to fix this in **export_users.jsp**

I'm also *very* reluctant to change tag behavior to enable unicode escaping by default. Here's why:  **unicode escaping is *twice* as expensive as JS escaping**, and grows linearly with the string length. I wrote a simple [script](https://gist.github.com/dsanz/8cc4e885422d7e120c58c66dd854197b) which yields the following:
> Translation: Mi
> Iterations : 1000000
>  . LanguageUtil.get() took 90ms
>  . escapeJS(LanguageUtil.get()) took 86ms
>  . UnicodeLanguageUtil.get() took  143ms
> 
> Translation: Los resultados de arriba incluyen usuarios que no tienen los campos requeridos (nombre de usuario, contraseña, dirección de correo electrónico, nombre, y apellido). Estos usuarios no serán importados hasta que se completen estos campos.
> Iterations : 1000000
>  . LanguageUtil.get() took 109ms
>  . escapeJS(LanguageUtil.get()) took 1665ms
>  . UnicodeLanguageUtil.get() took  3888ms
>

There's a significant improvement if we use HtmlUtl.escapeJS() instead of unicode escaping.  Indeed, we shall consider using it in the MessageTag too as currently we're using unicode inside every occurrence of `<liferay-ui:message>` inside `<aui:script>` (not for this fix, but as a perf improvement)

Moreover, both escaping functions have a O(n) cost being n the string length. So, unless we cache this somehow, we're wasting a precious time every time we escape a translation. We may consider using singleVM to cache the escapings as translations are fixed strings

I know minification can mitigate this, but stil we have a ton of <aui:script> in the middle of JSPs, I'm not sure we minify them

@jbalsas please take this as a suggestion to explore, it's not related to this fix in particular. cc/ @antonio-ortega
Best

**Comment by rolandpakai** [comment]
New PR: https://github.com/jbalsas/liferay-portal/pull/1961

**Pull request closed without merging**
